version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: air_tickets
    volumes:
      - ./db_structure.sql:/docker-entrypoint-initdb.d/db_structure.sql

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planes_technical_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: root
      COUCHBASE_ADMINISTRATOR_PASSWORD: root
